const bip39 = require('bip39');
const { Wallet } = require('ethers');
const bitcoin = require('bitcoinjs-lib');
const { Keypair } = require('@solana/web3.js');
const { derivePath } = require('ed25519-hd-key');
const bip32 = require('@scure/bip32');
const secp = require('@noble/secp256k1');
const bech32 = require('bech32');
const crypto = require('crypto');

const mnemonic = bip39.generateMnemonic(256);
const seed = bip39.mnemonicToSeedSync(mnemonic);

console.log("## Secure Multi-Chain Wallets Generated ##");
console.log("");
console.log("**Mnemonic (24 words - CRITICAL: Backup offline, never share!)**");
console.log(mnemonic);
console.log("");
console.log("**ETH Address:** " + Wallet.fromPhrase(mnemonic).address);
console.log("");
const node = bip32.HDKey.fromMasterSeed(seed).derive("m/84'/0'/0'/0/0");
const pubKey = secp.getPublicKey(node.privateKey, true);
const sha = crypto.createHash('sha256').update(pubKey).digest();
const ripemd = crypto.createHash('ripemd160').update(sha).digest();
const words = bech32.bech32.toWords(ripemd);
const btcAddress = bech32.bech32.encode('bc', [0, ...words]);
console.log("**BTC Address (Native SegWit bech32):** " + btcAddress);
console.log("");
const solSeed32 = seed.slice(0, 32);
const solDerived = derivePath("m/44'/501'/0'/0'", solSeed32);
const solKeypair = Keypair.fromSeed(solDerived.key);
console.log("**SOL Address:** " + solKeypair.publicKey.toBase58());
console.log("");
console.log("**Balances:** 0 ETH, 0 SOL, 0 BTC (freshly generated)");
console.log(""); 
console.log("Derivation paths:");
console.log("- ETH: m/44'/60'/0'/0/0");
console.log("- BTC: m/84'/0'/0'/0/0");
console.log("- SOL: m/44'/501'/0'/0' (first 32 bytes of seed)");
